config/routes.rb
Rails.application.routes.draw do
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  get 'welcome/index'
  root 'welcome#index'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  
  resources :articles do
     resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true

#					length: { minimum: 5}

	def goalDifference
		goalDifference = (goals_for - goals_against)
					#update goal_difference in database with its value
		update_column(:goal_difference, goalDifference)	

	end
	
	def points
		points = (games_won * 3) + (games_drew * 1)
		update_column(:total_points, points) 	#update total_points in database with its value
	end


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :first_name,
  				presence: true
  validates :last_name,
  				presence: true
  validates :email,
  				presence: true,
  				uniqueness: true,
  				format: {
  					with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  				}
  def to_s
  	"#{first_name} #{last_name}"
  end

  def initialiseScore
    update_column(:score, 0)  
  end

  def isAdmin
    update_column(:admin, true)
  end

  def isNotAdmin
    update_column(:admin, false)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private
  def current_user
  	User.where(id: session[:user_id]).first
  end
  helper_method :current_user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authorize, except: [:show, :index]

	def index

		@articles = Article.order(total_points: :desc, goal_difference: :desc)
	end

	def show
		@article = Article.find(params[:id])
#		@article = Article.find(:all, :order => 'created_at')
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			@article.goalDifference 	#Ensure the goal difference figure is updated too
			@article.points 			#Ensure points figure is also updated
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end


	private
		def article_params
			params.require(:article).permit(:title, :text, :games_played, :games_won, :games_drew, :games_lost, :goals_for, :goals_against, :goal_difference, :total_points)
		end

		def authorize
			if (current_user.nil?) || (current_user.admin == false)
				redirect_to sessions_new_path, alert: "Not authorized please log in!"	
			end
		end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: "dhh", password: "secret",
	only: :destroy

	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end

	private 
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to root_url, notice: 'Logged in!'
  	else
  		render :new
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'User was successfully created.'
      if @user.email == "skilcawley@gmail.com"
        @user.isAdmin
      else
        @user.isNotAdmin
      end
      @user.initialiseScore
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :admin)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

	<% if @article.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@article.errors.count, "error") %>
				prohibited
				this article from being saved:
			</h2>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :team %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :played %><br>
		<%= f.number_field :games_played %>
	</p>

	<p>
		<%= f.label :won %><br>
		<%= f.number_field :games_won %>
	</p>

	<p>
		<%= f.label :drew %><br>
		<%= f.number_field :games_drew %>
	</p>

	<p>
		<%= f.label :lost %><br>
		<%= f.number_field :games_lost %>
	</p>

	<p>
		<%= f.label :"goals for" %><br>
		<%= f.number_field :goals_for %>
	</p>

	<p>
		<%= f.label :"goals against" %><br>
		<%= f.number_field :goals_against %>
	</p>

<!--	<p>
		<%= f.label :"goal difference" %><br>
		<%= f.number_field :goal_difference %>
	</p>

	<p>
		<%= f.label :points %><br>
		<%= f.number_field :total_points %>
	</p>		-->

	<p>
		<%= submit_tag("Create Team") %>		<!--	<%= f.submit %>	-->
	</p>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1> Great Southern Hotel Sligo Super League</h1>

<strong style="font-size:20px">Live Games: </strong><br>
<textarea cols="30" rows="10" name= "LiveGames">

</textarea> 
<br>
<br>
<br>
<br>
<strong style="font-size:20px">League Table: </strong><br>


</p>
<table>
	<tr>
		<th>Team</th>
		<th>P</th>
		<th>W</th>
		<th>D</th>
		<th>L</th>
		<th>F</th>
		<th>A</th>
		<th>GD</th>
		<th>Points</th>

		<th colspan="9"></th>
	</tr>



	<% @articles.each do |article| %>	
	
		<tr>
			<td><%= article.title %></td>
			<td><%= article.games_played %></td>
			<td><%= article.games_won %></td>
			<td><%= article.games_drew %></td>
			<td><%= article.games_lost %></td>
			<td><%= article.goals_for %></td>
			<td><%= article.goals_against %></td>
			<td><%= article.goal_difference %></td>
			<td><%= article.total_points %></td>
			<td><%= link_to 'Show', article_path(article) %></td>
			<td><%= link_to 'Edit', edit_article_path(article) %></td>
			<td><%= link_to 'Delete', article_path(article),
					method: :delete,
					data: { confirm: 'Are you sure?'} %></td>
			
		</tr>
	<% end %>
</table>
<br>
<%= link_to 'Enter New Team', new_article_path %>
<%= link_to 'Back', welcome_index_path %>
<%= link_to 'Users', users_path %>

app/views/articles/new.html.erb
<h1>Enter New Team</h1>

<%= render 'form' %>	
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
	<strong>Team:</strong>
	<%= @article.title %>
</p>

<p>
	<strong>Played:</strong>
	<%= @article.games_played %>
</p>

<p>
	<strong>Won:</strong>
	<%= @article.games_won %>
</p>

<p>
	<strong>Drew:</strong>
	<%= @article.games_drew %>
</p>

<p>
	<strong>Lost:</strong>
	<%= @article.games_lost %>
</p>

<p>
	<strong>For:</strong>
	<%= @article.goals_for %>
</p>

<p>
	<strong>Against:</strong>
	<%= @article.goals_against %>
</p>

<p>
	<strong>Difference:</strong>
	<%= @article.goal_difference %>
</p>

<p>
	<strong>Points:</strong>
	<%= @article.total_points %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment: </h2>
<%= render 'comments/form' %>



<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
	<strong>Commenter:</strong>
	<%= comment.commenter %>
</p>

<p>
	<strong>Comment:</strong>
	<%= comment.body %>
</p>

<p>
	<%= link_to 'Destroy Comment', [comment.article, comment],
				method: :delete,
				data: { confirm: 'Are you sure?'} %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
	<p>
		<%= f.label :commenter %><br>
		<%= f.text_field :commenter %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalYearProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<div id="user_header">
	<% if current_user %>
		Logged in as <%= current_user.email %>
		<%= link_to "Log Out", logout_path %>
	<% else %>
		<%= link_to "Sign Up", signup_path %> or
		<%= link_to "Log In", login_path %>
	<% end %>
</div>
<% flash.each do |key, value| %>
	<%= content_tag(:div, class: "alert alert-#{key}") do %>
		<p><%= value %></p>
	<% end %>
<% end %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Admin</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= user.score %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/users/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Sligo Leitrim District League</h1>
	<strong style="font-size:20px"> Leagues: </strong><br>

<%= link_to 'Great Southern Hotel Sligo Super League', controller: 'articles' %> <br>
<%= link_to 'Sligo Pallets Premier League', controller: 'articles' %>